name: Bug Report
description: File a bug report
labels: ["type.Bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How to reproduce?
      description: What are the steps to reproduce this bug?
      placeholder: Tell us how the bug happened.
    validations:
      required: true
  - type: dropdown
    id: bug-severity
    attributes:
      label: Bug Severity
      description: How severe is the bug's effect on the product's functionality?
      multiple: false
      options:
        - label: severity.VeryLow
        - label: Low
        - label: Medium
        - label: High
    validations:
      required: true
