name: Bug Report
description: File a bug report
title: "Bug:"
labels: ["type.Bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How to reproduce?
      description: What are the steps to reproduce this bug?
      placeholder: Tell us how the bug happened.
      value: "1.\n2.\n3."
    validations:
      required: true