name: add label to issue
on: issues
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: View issue information
        uses: andymckay/labeler@master
        with:
          add-labels: "severity.VeryLow"