name: add label to issue
on: issues
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: View issue information
        run: |
          Set-Variable -Name MyVar -Value ${{github.event.issue.body}};
          echo "$MyVar"
      - name: Add Label
        uses: andymckay/labeler@master
        with:
          add-labels: "severity.VeryLow"