name: add label to issue
on: issues
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: View issue information
        run: |
          x = ${{github.event.issue.body}}; 
          $MyVar = x;
          echo "$MyVar"
      - name: Add Label
        uses: andymckay/labeler@master
        with:
          add-labels: "severity.VeryLow"