name: PR Updates

on:
  pull_request:
    types: [opened, edited, ready_for_review, review_requested, reopened]
  pull_request_review_comment:
    types: [created]

jobs:
  dummy-workflow:
    runs-on: ubuntu-latest
    name: dummy workflow
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "title": "${{ github.event.pull_request.title }}", "creator:" "${{ github.actor }}"}'
      - name: Explanation
        run: echo "this is a dummy workflow that triggers a workflow_run; it's necessary because otherwise the repo secrets will not be in scope for externally forked pull requests"